name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Ручной запуск

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        ADMIN_CHAT_ID: ${{ secrets.TG_BOT_ADMIN }}
        CHANNEL_CHAT_ID: ${{ secrets.TG_CHANNEL_ID }}

        script: |
          cd /opt/car-bot

          # Restart containers
          docker-compose down
          docker compose build
          docker-compose up -d
